### ISSUE TITLE
Resizing images

### ISSUE THREAD

**Issue by bkj** [yahoo/crow#3]
Hi -- how does `crow` deal with resizing images?  I was under the impression that VGG16 took a 224x224 image as input, but it doesn't look like anything's being resized in the code.

Thanks
Ben

**Comment by bkj** [comment]
Ah I see that VGG16 in Caffe will take variable sized images, and thus you end up with variable size feature maps.  That seems mildly odd though -- feeding in the same image at two different scales would presumably yield a different embedding.  Any thoughts on whether it makes sense to scale everything before running through `crow`?

**Comment by pumpikano** [comment]
We reported some comparisons on this topic in our paper, but the takeaway is that, at least on benchmark datasets, keeping the full resolution is worth ~5-10% mAP compared to 224x224 and only ~2-4% mAP compared to 586x586. In general, the higher resolution, the better mAP, with diminishing returns. Depending on the demands of your application, it may make sense to resize to a fixed size (e.g. especially if it enables efficient batching on GPU hardware or the like). The version here keeps the full resolution for the best possible retrieval performance with an implicit assumption that all photos you might extract features for are roughly the same size.

**Comment by bkj** [comment]
Excellent thanks.  586x586 sounds reasonable for this application in that case -- the original images are huge but sortof variably sized.  As an anecdote, scaling them to a fixed size __appeared__ to give a nontrivial bump in performance, compared to passing them in at a variety of sizes.

**Comment by xiaozhi2015** [comment]
“The version here keeps the full resolution for the best possible retrieval performance”， but the input size is 10 * 3 * 224 * 224 in VGG_ILSVRC_16_pool5.prototxt.  Will it resize the img into 224 * 224 automatically when running?
The problem I met is the poor performance when applying to imgs whose "height > width".
@pumpikano
